# Generated by Django 2.2.12 on 2020-04-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StationSalesOverall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(blank=True, max_length=255, null=True)),
                ('account', models.CharField(blank=True, max_length=255, null=True)),
                ('site', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('ad_spend', models.FloatField(blank=True, null=True)),
                ('ad_sales', models.FloatField(blank=True, null=True)),
                ('acos', models.FloatField(blank=True, null=True)),
                ('shop_sales', models.FloatField(blank=True, null=True)),
                ('spend_rate', models.FloatField(blank=True, null=True)),
                ('sale_rate', models.FloatField(blank=True, null=True)),
                ('update_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'station_sales_overall',
                'managed': False,
            },
        ),
    ]
