# Generated by Django 2.2.12 on 2020-04-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StationSalesOverall',
            fields=[
                ('station', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('account', models.CharField(blank=True, max_length=255, null=True)),
                ('site', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('ad_spend', models.FloatField(blank=True, null=True)),
                ('ad_sales', models.FloatField(blank=True, null=True)),
                ('acos', models.FloatField(blank=True, null=True)),
                ('shop_sales', models.CharField(blank=True, max_length=255, null=True)),
                ('spend_rate', models.CharField(blank=True, max_length=255, null=True)),
                ('sale_rate', models.CharField(blank=True, max_length=255, null=True)),
                ('update_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'station_sales_overall',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
