# Generated by Django 2.2.12 on 2020-04-28 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_onlystationinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
